-- MySQL Script generated by MySQL Workbench
-- Mon Jun  6 13:43:08 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema traktor
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema traktor
-- -----------------------------------------------------
CREATE SCHEMA  "traktor"  ;

-- -----------------------------------------------------
-- Table "traktor"."crop"
-- -----------------------------------------------------
CREATE TABLE  "traktor"."crop" (
  "id" INT NOT NULL ,
  "name" VARCHAR(45) NULL,
  PRIMARY KEY ("id"));


-- -----------------------------------------------------
-- Table "traktor"."crop_variety"
-- -----------------------------------------------------
CREATE TABLE  "traktor"."crop_variety" (
  "id" INT NOT NULL ,
  "variety" VARCHAR(45) NULL,
  "crop_id" INT NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fk_crop_variety_crop"
    FOREIGN KEY ("crop_id")
    REFERENCES "traktor"."crop" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table "traktor"."market"
-- -----------------------------------------------------
CREATE TABLE  "traktor"."market" (
  "id" INT NOT NULL ,
  "name" VARCHAR(45) NULL,
  "latitude" DECIMAL(9,6) NULL,
  "longitude" DECIMAL(9,6) NULL,
  PRIMARY KEY ("id"));


-- -----------------------------------------------------
-- Table "traktor"."price"
-- -----------------------------------------------------
CREATE TABLE  "traktor"."price" (
  "id" INT NOT NULL ,
  "price" DECIMAL(6,2) NULL,
  "submit_ts" TIMESTAMP NULL,
  "crop_variety_id" INT NOT NULL,
  "market_id" INT NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fk_price_crop_variety1"
    FOREIGN KEY ("crop_variety_id")
    REFERENCES "traktor"."crop_variety" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "fk_price_market1"
    FOREIGN KEY ("market_id")
    REFERENCES "traktor"."market" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table "traktor"."daily"
-- -----------------------------------------------------
CREATE TABLE  "traktor"."daily" (
  "id" INT NOT NULL ,
  "daily_average" DECIMAL(6,2) NULL,
  "current_date" TIMESTAMP NULL,
  "crop_variety_id" INT NOT NULL,
  "market_id" INT NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fk_analytics_crop_variety1"
    FOREIGN KEY ("crop_variety_id")
    REFERENCES "traktor"."crop_variety" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "fk_daily_market1"
    FOREIGN KEY ("market_id")
    REFERENCES "traktor"."market" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table "traktor"."yearly"
-- -----------------------------------------------------
CREATE TABLE  "traktor"."yearly" (
  "id" INT NOT NULL ,
  "yearly_average" DECIMAL(6,2) NULL,
  "year" INT NULL,
  "crop_variety_id" INT NOT NULL,
  "market_id" INT NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fk_yearly_crop_variety1"
    FOREIGN KEY ("crop_variety_id")
    REFERENCES "traktor"."crop_variety" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "fk_yearly_market1"
    FOREIGN KEY ("market_id")
    REFERENCES "traktor"."market" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table "traktor"."global_prices"
-- -----------------------------------------------------
CREATE TABLE  "traktor"."global_prices" (
  "id" INT NOT NULL ,
  "current_average" DECIMAL(6,2) NULL,
  "previous_average" DECIMAL(6,2) NULL,
  "crop_variety_id" INT NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fk_global_prices_crop_variety1"
    FOREIGN KEY ("crop_variety_id")
    REFERENCES "traktor"."crop_variety" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


DROP SEQUENCE IF EXISTS "traktor.crop_id_sequence";
CREATE SEQUENCE  "traktor.crop_id_sequence";
DROP SEQUENCE IF EXISTS "traktor.crop_variety_id_sequence";
CREATE SEQUENCE  "traktor.crop_variety_id_sequence";
DROP SEQUENCE IF EXISTS "traktor.market_id_sequence";
CREATE SEQUENCE  "traktor.market_id_sequence";
DROP SEQUENCE IF EXISTS "traktor.price_id_sequence";
CREATE SEQUENCE  "traktor.price_id_sequence";
DROP SEQUENCE IF EXISTS "traktor.daily_id_sequence";
CREATE SEQUENCE  "traktor.daily_id_sequence";
DROP SEQUENCE IF EXISTS "traktor.yearly_id_sequence";
CREATE SEQUENCE  "traktor.yearly_id_sequence";
DROP SEQUENCE IF EXISTS "traktor.global_prices_id_sequence";
CREATE SEQUENCE  "traktor.global_prices_id_sequence";
